@startuml
left to right direction

actor Employee
actor Manager
actor Member
actor HR <<System>>

Employee <|- Manager
Employee <|- Member

rectangle "Project Management System" {
  Employee --> (Generate a report)
  Employee --> (Create a new task)
  Employee --> (Assign a Task)
  (Assign a Task) -- HR
  Manager  --> (Create a new project)
  (Create a new project) -- HR
  Member   --> (Make progress on a task)
}

@enduml
